fix: When we cant find some contentMedia dont fail. Just carry on.
whitespace-se/wordpress-plugin-wp-graphql-extras pull request #1
Opened 2021-09-08 15:00 UTC by johanwestin

2021-09-10 13:04 UTC, jeanfredrik requested changes
The array should probably be filtered to, so there’s no empty elements

2021-10-07 13:32 UTC, johanwestin commented
I don't think the `preg_match_all` function can return empty items. 

`preg_match_all("/wp-(?:image|caption)-(\d+)/", $content, $matches);`

We are running `array_map` on `matches[1]`. 

That array will never contain empty items. the problem here is that the migration process is not 100% reliable and sometimes there are missing information in the database.

2021-10-07 13:36 UTC, jeanfredrik commented
If any `$post` is empty, the array will contain a `null` element. Those should be filtered out. If `$post` is never empty, then we don’t need to change the code in the first place, right?

2021-10-07 13:49 UTC, johanwestin commented
Array filter implemented here https://github.com/whitespace-se/wordpress-plugin-wp-graphql-extras/pull/1/commits/3a3d23872af1a0a8ae51ed21bdc40fa926f2616f

2021-10-07 14:06 UTC, jeanfredrik requested changes

2021-10-07 14:06 UTC, jeanfredrik commented on whitespace-wp-graphql-extras.php
> +        return array_filter($posts, fn($i) => !empty($i));
You can skip the second argument. The effect will be the same.

2021-10-12 07:07 UTC, johanwestin commented on whitespace-wp-graphql-extras.php
> +        return array_filter($posts, fn($i) => !empty($i));
Done. Also removed the $posts variable. 

It was only confusing.

2021-10-12 07:24 UTC, jeanfredrik approved these changes

2021-10-12 07:24 UTC, merged

2021-10-12 07:27 UTC, jeanfredrik commented
Released in [v0.1.2](https://packagist.org/packages/whitespace-se/wordpress-plugin-wp-graphql-extras#v0.1.2)